const data = {
  users: [
    {
      name: 'Ahnaf Tahmid',
      email: 'ahnaf@dummy1.com',
      password: 'were5645%^',
      phone: '+821414447',
      address: 'Mountain View, CA, USA',
      image: 'https://randomuser.me/api/portraits/men/1.jpg',
    },
    {
      name: 'Jordan Boyd',
      email: 'andrewkelly@wagner.com',
      phone: '+1-839-956-9140x77150',
      address: 'Unit 1177 Box 2499\nDPO AA 40997',
      password: 'AI(4U9m+0pg!',
      image: 'https://randomuser.me/api/portraits/men/2.jpg',
    },
    {
      name: 'David Osborn',
      email: 'amber68@gmail.com',
      phone: '418.470.0385',
      address: 'USNS Grimes\nFPO AA 08842',
      password: 'T8+RCSQr$g57',
      image: 'https://randomuser.me/api/portraits/men/3.jpg',
    },
    {
      name: 'Dominic Hess',
      email: 'jennifer77@sanchez-barker.biz',
      phone: '+1-487-012-7714x2857',
      address: '325 Sara Port\nPageborough, CO 18915',
      password: 'A)$zb8Ko_^B&',
      image: 'https://randomuser.me/api/portraits/men/4.jpg',
    },
    {
      name: 'Craig Wood',
      email: 'hernandezcory@hotmail.com',
      phone: '143-097-7124x909',
      address: '436 Christopher Forge Apt. 599\nNew Taylortown, WV 90754',
      password: '2i^8Moj#k8_p',
      image: 'https://randomuser.me/api/portraits/men/5.jpg',
    },
    {
      name: 'Benjamin Smith',
      email: 'robertsmelissa@payne-farley.com',
      phone: '+1-638-871-0242x693',
      address: '6846 Kathryn Run Suite 481\nFigueroabury, OH 02808',
      password: ')89Y!3Gc+A12',
      image: 'https://randomuser.me/api/portraits/men/6.jpg',
    },
    {
      name: 'Jeffrey Thompson',
      email: 'sharpsharon@hotmail.com',
      phone: '(231)014-3294x53750',
      address: 'Unit 3795 Box 5853\nDPO AA 02809',
      password: 'e&H9Bw#jUl%1',
      image: 'https://randomuser.me/api/portraits/men/7.jpg',
    },
    {
      name: 'Kenneth Lopez',
      email: 'amberlane@gmail.com',
      phone: '(599)581-2795x530',
      address: '334 Kelly Throughway\nLloydhaven, HI 12526',
      password: '!cmD*vTij6mB',
      image: 'https://randomuser.me/api/portraits/men/8.jpg',
    },
    {
      name: 'Tyler Morgan',
      email: 'princejeffrey@hotmail.com',
      phone: '(685)690-7949',
      address: '1724 Acevedo Way Apt. 850\nEast Lawrence, ND 31199',
      password: 'r&I5MUCn%!7*',
      image: 'https://randomuser.me/api/portraits/men/9.jpg',
    },
    {
      name: 'Scott Davenport',
      email: 'padams@hotmail.com',
      phone: '108-449-6222x570',
      address: '9522 Mann Islands\nWest Heather, DE 38726',
      password: 'fmdQYmq2^B52',
      image: 'https://randomuser.me/api/portraits/men/10.jpg',
    },
    {
      name: 'David Jackson',
      email: 'weavermark@gmail.com',
      phone: '(544)961-1506',
      address: '565 Vazquez Isle\nNorth Kyleshire, NH 21949',
      password: '+4!FlBTacjij',
      image: 'https://randomuser.me/api/portraits/men/11.jpg',
    },
  ],
};
export default data;
